name: Python package

on:
- push
- pull_request

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4

    - name: Install additional Python interpreters
      run: |
        sudo add-apt-repository ppa:deadsnakes/ppa
        sudo apt-get update
        sudo apt-get install python3.7 python3.7-distutils python3.9 python3.9-distutils python3.10 python3.10-distutils

    - name: Install ffmpeg
      run: sudo apt-get install ffmpeg

    - name: Install tox
      run: |
        python -m pip install --upgrade pip
        python -m pip install tox

    - name: Run tox
      run: python -m tox --skip-missing false
